Update release workflow to check action version (#54)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,6 +1,9 @@
 name: release
 
 on:
+  pull_request:
+    paths:
+      - .github/workflows/release.yml
   push:
     tags:
       - 'release/*'
@@ -11,7 +14,6 @@ permissions:
 env:
   CARGO_INCREMENTAL: 0
   CARGO_NET_RETRY: 10
-  DEBIAN_FRONTEND: noninteractive
   RUST_BACKTRACE: short
   RUSTUP_MAX_RETRIES: 10
 
@@ -26,12 +28,19 @@ jobs:
         id: parse-tag
         run: |
           ref="${{ github.ref }}"
-          echo "::set-output name=version::${ref#refs/tags/release/}"
-      - run: apt update && apt install -y jq
+          if [[ "$ref" = refs/tags/release/* ]]; then
+            v="${ref#refs/tags/release/}"
+          else
+            v=""
+          fi
+          echo "::set-output name=version::$v"
+
       - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
-      - run: cargo fetch
-      - name: check crate and tag version
+
+      - name: check crate version
+        if: steps.parse-tag.outputs.version != ''
         run: |
+          apt update && apt install -y jq
           v=$(cargo metadata --frozen --format-version=1  | jq -r '.packages[] | select(.name == "cargo-action-fmt") | .version')
           echo "cargo.toml v$v"
           echo "tag ${{ steps.parse-tag.outputs.version }}"
@@ -40,14 +49,32 @@ jobs:
               exit 1
           fi
 
+      - name: check action version
+        if: steps.parse-tag.outputs.version != ''
+        run: |
+          curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64
+          chmod 755 /usr/local/bin/yq
+          v=$(yq .inputs.version.default action.yml)
+          echo "action.yml $v"
+          echo "tag ${{ steps.parse-tag.outputs.version }}"
+          if [ "v${v}" != "${{ steps.parse-tag.outputs.version }}" ]; then
+              echo "::error ::Action version ${v} does not match tag version ${{ steps.parse-tag.outputs.version }}"
+              exit 1
+          fi
+
+      - run: cargo fetch
       - name: cargo build
         run: |
           cargo build --release --frozen
           mv target/release/cargo-action-fmt target/cargo-action-fmt-x86_64-unknown-linux-gnu
 
+      - run: cargo publish --dry-run
+
       - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
+        if: steps.parse-tag.outputs.version != ''
         with:
           name: ${{ steps.parse-tag.outputs.version }}
           files: target/cargo-action-fmt-x86_64-unknown-linux-gnu
 
-      - run: cargo publish --token=${{ secrets.CRATESIO_TOKEN }}
+      - if: steps.parse-tag.outputs.version != ''
+        run: cargo publish --token=${{ secrets.CRATESIO_TOKEN }}
